### ISSUE TITLE
Include name of browser for each test

### ISSUE THREAD

**Issue by EddieBrunstedt** [jonasclaes/playwright-testmo-reporter#4]
Hello, and thank you for this wonderful library!

I can't seem to be able to figure out how to pass to testmo which browser each test is targeting in a nice way. Currently, the only way I've found is to use the `browserName` fixture in each test like this:
```ts
test('My test', async ({ page, browserName }) => {
  test.info().annotations.push({
    type: 'browser',
    description: browserName
  });
  //..
});
```
Which ends up like this in testmo:

![2023-12-06_13-27](https://github.com/jonasclaes/playwright-testmo-reporter/assets/7594223/f8102765-4c12-4d67-9d9f-7fdc487a866f)

But I am wondering if it would be possible to make the aggregation of info in this library to include this somehow automatically?

**Comment by jonasclaes** [comment]
Hello, @EddieBrunstedt!

Thank you for logging this issue.

I have come across the deficiency as well. My approach to that problem was to create a base test, and add a before each in my base test, which basically does as you describe there in the `test.info()` approach. That at least deduplicates this across the project.

However, I do value your idea to add this to the library, and as such, I will look into a possible solution for this problem.

I'll keep you posted.

If you have any ideas, please feel free to reach out!

Kind regards

**Comment by jonasclaes** [comment]
This has been added in v1.3.0. Please see the documentation for more information.
